[package]
name = "micro-drivers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.micro]
path = "../micro"

[dependencies.embedded-hal]
version = "1.0.0-alpha.5"
